# Generated by Django 2.0 on 2018-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_events_eventdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festmeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festname', models.CharField(max_length=300)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='Start Date')),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=300)),
                ('chief_guest1', models.CharField(max_length=200)),
                ('cheif_guest2', models.CharField(max_length=200)),
                ('chief_guest3', models.CharField(max_length=200)),
                ('registration_fee', models.IntegerField()),
                ('accomodation', models.CharField(max_length=1)),
                ('food', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='registration_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
