# Generated by Django 2.0 on 2018-09-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_students_username'),
        ('event', '0003_auto_20180924_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_register', to='event.Events')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_register', to='accounts.Students')),
            ],
        ),
    ]
