# Generated by Django 2.0 on 2018-09-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180927_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='festmeta',
            name='username',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
