# Generated by Django 2.0 on 2018-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_festmeta_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='festmeta',
            name='city',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festmeta',
            name='college_address',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festmeta',
            name='district',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festmeta',
            name='state',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
