# Generated by Django 2.0 on 2018-09-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_festmeta_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festmeta',
            old_name='collegewebstite',
            new_name='collegewebsite',
        ),
        migrations.RemoveField(
            model_name='festmeta',
            name='cheif_guest2',
        ),
        migrations.AddField(
            model_name='festmeta',
            name='chief_guest2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='festmeta',
            name='chief_guest1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='festmeta',
            name='chief_guest3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
