# Generated by Django 2.0 on 2018-10-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20180927_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='festmeta',
            name='branch',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
