# Generated by Django 2.0 on 2018-10-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_festmeta_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='festmeta',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='fest_register', to='event.Festmeta'),
            preserve_default=False,
        ),
    ]
