# Generated by Django 2.0 on 2018-10-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_registrations_festmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='regfeestatus',
            field=models.CharField(default='No', max_length=3),
            preserve_default=False,
        ),
    ]
