# Generated by Django 2.0 on 2018-09-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='firstname',
            field=models.CharField(default='Male', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='lastname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
