# Generated by Django 2.0 on 2018-09-25 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
